### ISSUE TITLE
reStructuredText README not rendered

### ISSUE THREAD

**Issue by hugovk** [frostming/oven#6]
https://oven.fming.dev/package/python-dateutil looks like:

![image](https://github.com/frostming/oven/assets/1324225/67203549-7a8d-4531-baeb-4a61fa56f050)

https://pypi.org/project/python-dateutil/ looks like:

![image](https://github.com/frostming/oven/assets/1324225/12dca2d1-ef32-4329-ae19-76abcc937a18)

In case it's useful, PyPI/Warehouse uses https://pypi.org/project/readme-renderer/ to render Markdown, reST and plain text READMEs.

**Comment by frostming** [comment]
Unfortunately there isn't a good alternative in node ecosystem.

Porting that library to node will be too much effort.

**Comment by hugovk** [comment]
According to https://py-code.org/stats, use of RST (5,906) is about a 22% of that of MD (26,732):

![image](https://github.com/frostming/oven/assets/1324225/360db674-9b88-4906-9e4f-b6e66cc16ffd)

MD use is growing, RST use is about constant. This suggests new packages use MD, but older or more-established packages use RST.

---

Looking at the [top 8k packages](https://dev.to/hugovk/how-to-search-5000-python-projects-31gk), RST use is about 70% of that of MD (packages with README.rst in root: 2,845; with README.md: 4,036).

So whilst MD is also more popular here, a visitor is much more likely to see an RST when checking popular projects. And I think most people will look up popular projects.

**Comment by tssujt** [comment]
@frostming Is using [Pyodide](https://github.com/pyodide/pyodide) with [readme-renderer](https://pypi.org/project/readme-renderer/) acceptable? Here is a demo.

https://github.com/tssujt/python-package-readme-playground
https://tssujt.github.io/python-package-readme-playground/

**Comment by frostming** [comment]
> @frostming Is using [Pyodide](https://github.com/pyodide/pyodide) with [readme-renderer](https://pypi.org/project/readme-renderer/) acceptable? Here is a demo.

@tssujt that works

**Comment by hugovk** [comment]
It "works" but takes about 5 seconds to load and render, compared to ~zero for Markdown.

Are any of these packages usable? 

https://www.npmjs.com/search?q=restructuredtext

**Comment by frostming** [comment]
> ww.npmjs.com/search?q=restructuredtext



No, unfortunately. Speed is not the main concern for now and it is rendered at client side, i.e. doesn't block other contents
